packages:
  - apps/*
  - packages/*
overrides:
  postcss: 8.5.25
  sharp: 0.35.3
allowBuilds:
  '@clerk/shared': false
  bufferutil: false
  core-js: false
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: false
